spring.application.name: gpb

httpclient:
  back-service-uri: http://84.201.135.27:8080/v2
  maxConPerRoute: 20
  maxConTotal: 50
  connectionTimeoutMs: 5000
  requestTimeoutMs: 30000

features:
  backendServiceEnabled: true